### ISSUE TITLE
Add version information/most recent change date for individual resources included in downloadable .json file

### ISSUE THREAD

**Issue by ojahnn** [cu-clear/UVI#39]
The download area on the UVI website at [https://uvi.colorado.edu/nlp_applications#download](https://uvi.colorado.edu/nlp_applications#download) lets the user select the resources to include. The download takes the form of a json file with each selected resource as one key, and the contents of that resource as the key's corresponding value.

This is great, especially for working with the mappings! But what's missing is an indication of the version of each resource, or a link to the version of the resource that was used to generate the json, or just the date of the latest changes that were made to the resource. Specifically, I've been looking at some VerbNet classes and noticed **differences between the data included in the UVI download, and the data included in VerbNet 3.3 as offered for downloading [here](https://verbs.colorado.edu/verbnet/)**. I can't figure out which of these versions is supposed to be the "canonical" one, or which one has most recently been updated.

Is this information available somewhere on the UVI website and I just didn't find it? Or would it need to be added? Optimally I'd like it inside the json file itself, but otherwise it would also be helpful if the last update date showed up on the UVI website, maybe near the download button. This would also make it much easier to cite the data when using it for research.

**Comment by piyush-k-mishra** [comment]
UVI is using the latest version of [VerbNet](https://github.com/cu-clear/verbnet) i.e. 3.4. All the future changes related to VerbNet in the UVI will be result of changes made to this project. Currently, this project contains 3.3 and 3.4 (master). The prior versions can be accessed from the link you have shared. 

We'll soon add the version information on the download page of UVI and will provide access to other versions as well. Also there will be a README file in the UVI which will highlight the key changes in different VN versions.
